### ISSUE TITLE
Change to maximum class value format in legend/HTML Template for Legend as an Option

### ISSUE THREAD

**Issue by ConsultBuckner** [balladaniel/leaflet-dataclassification#3]
First, absolutely amazing plug-in. I was banging my head against the wall trying to write an algo for a Jenks bin distribution. This is a life saver. 

I find the highest class label in the legend confusing as the less-than symbol comes after the value. I think it makes more sense before the value and it should be a greater-than symbol, like the minimum class label in the legend but with a greater-than symbol. So this:   > {value}  instead of:  {value} <   

Or perhaps the value with a '+' after it such as:  {value} +

![image](https://github.com/balladaniel/leaflet-dataclassification/assets/38384853/d2f24c8c-973d-46a1-97bb-bb5b58350944)

Just that little change would be great (I can adjust my local copy of the script to do that for my app, but it seems like it could be more of a bug than feature request, thus to be added to the repo). 

And along this thought, perhaps an HTML template could be included as an option to provide full customization of the legend key values?

**Comment by balladaniel** [comment]
Hi! Thanks for trying the plugin, I'm glad it works well for you. Also, thanks for your feedback!

- max. class: upon first sight, I found the current way quite logical and legible, since the values are as "low"-"high" pairs from top to bottom, and once we reach the maximum (top row), it is the "high" value that is missing. That's why I thought the comparison mark "<" would make sense after the last "low" value to keep the left-to-right / low-to-high order. I can see why you would want to have it on the left as an ">", though. To maximise customizability (as one of my goals), I will look into it and add an option to be able to set this as wished. 
- legend key value template: it is a great suggestion, will definitely look into it (and maybe tackle the max. class >/< character customization too, to "kill 2 birds with one stone").

If you have anything else to report/suggest, I would be glad to hear that!

**Comment by ConsultBuckner** [comment]
Nice! I understand your logic - it was tripping me up when vocalizing it aloud to myself. It was a super easy, quick fix on my local copy of the module. 

I did run into another issue that was specific to my implementation, which I was able to fix. I dynamically create two different layer groups with two different legends when the user selects from a large list of data variables derived from a feature set of US States and set of Counties. I add them to the map and remove them according to map zoom by the user. I found that if I zoomed and panned the map several times in quick succession while at the County zoom level, which has around 3500 features, the legend would not remove itself before the new legend for the other feature set was created - thus leaving me with two legends, then three etc.. 
I think it had something to do with the re-use of the id property assigned to the legend in your module as that is how it is referenced with a find function on _legends array. Sometimes that function would return a null and crash the page script all together. 

So I just added a check for null, and if so to run a forEach on the _legends array, removing each from the map (I am not sure what scenario would require multiple legends, fwiw).
![image](https://github.com/balladaniel/leaflet-dataclassification/assets/38384853/5fb8576c-2630-4b35-ba7d-640939b446a6)

I have one more odd thing that I am trying to work out (btw, sorry all of this is in this one thread, I can separate them out). When replicating the code from the polygon example, regarding the tooltip on mouse hover, when I implement this, I get a 3 pixel black border with perhaps 4px radius around the extent of a feature when I click and drag the map around to pan. It could be from another plug-in interacting somehow, not sure yet.
![image](https://github.com/balladaniel/leaflet-dataclassification/assets/38384853/de47e6ef-3739-4f98-b702-793b418372f5)

**Comment by samanbey** [comment]
Hey,

> I have one more odd thing that I am trying to work out (btw, sorry all of this is in this one thread, I can separate them out). When replicating the code from the polygon example, regarding the tooltip on mouse hover, when I implement this, I get a 3 pixel black border with perhaps 4px radius around the extent of a feature when I click and drag the map around to pan. It could be from another plug-in interacting somehow, not sure yet. It isn't related to the mousemove event handler, but rather with the .bindTooltip function.

This is an interference with Chrome's built-in CSS rules. Theres a discussion about it e.g. here: 
https://gis.stackexchange.com/questions/447502/prevent-leaflet-map-from-showing-rectangle-around-layer-on-click

The workaround is to add one more css rule to your code:
```
path.leaflet-interactive:focus {
    outline: none;
}
```

**Comment by ConsultBuckner** [comment]
Yes! I just now came across the same solution from a different discussion. I am rendering the map in a WebView2 control in a WinForm desktop app which is Edge-based, but uses Chromium under the hood. That was a bit of a rabbit hole for a few :)

**Comment by balladaniel** [comment]
@ConsultBuckner You can now use custom HTML templates for formatting legend rows however you like. Documentation updated to include the new option, please have a look. Relevant commit: d8965d6
